# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=users.utils.upload_location),
        ),
    ]
